#!/bin/sh
# vim: ft=sh ts=4 sw=4 et

. /workspace/drone/tests/checks/utils

main() {
    local errors;
    local modules; modules=$(get_modules)

    for module in $modules
    do
        errors=$(flake8 --config=/workspace/drone/coog/tox.ini "/workspace/drone/coog/modules/$module")

        if [ ${#errors} -eq 0 ]
        then
            echo "No flake8 error detected, good job!"
        else
            echo "$errors" && return 1
        fi
    done
}

main
