#!/bin/sh
# vim: ft=sh ts=4 sw=4 et

init_bin() {
    echo "1. Init bin"
    ln -s /drone/src/tryton/bin/trytond /usr/local/bin/trytond
    ln -s /drone/src/trytond/bin/trytond-admin /usr/local/bin/trytond-admin
}

init_conf() {
    echo "2. Init conf"
    {
        echo "[database]"
        echo "uri = postgresql://postgres:postgres@database:5432"
        echo "[env]"
        echo "testing = True"
        echo "[async]"
        echo "rq = redis://127.0.0.1:6379/1"
        echo "[cache]"
        echo "uri = redis://redis:6379/0"
    } > /drone/src/conf/trytond.conf
}

_link_modules() {
    find /drone/src/trytond/trytond/modules -type l -delete
    ln -s "/drone/src/trytond-modules/modules/"* . || return 1
    ln -s "/drone/src/coog/modules/"* . || return 1
    if [ "$DRONE_REPO_NAME" = "customers" ]
    then
        ln -s "/drone/src/customers/modules/"* . || return 1
    else
        return 0
    fi
}

link_modules() {
    echo "3. Link modules"
    (cd /drone/src/trytond/trytond/modules && _link_modules)
}

check_module() {
    echo "Test $1"
    if [ ! "$1" = "global_tests" ]; then
        LOG_LEVEL=DEBUG python -W ignore \
            /drone/src/trytond/trytond/tests/run-tests.py \
            -c /drone/src/conf/trytond.conf -vv -m "$1"
    else
        echo "    global_tests bypassed for performance reason"
    fi
}

check_modules() {
    echo "4. Test modules"
    unset DB_NAME
    unset TRYTOND_CACHE_CLASS
    local modules
    modules=$(/drone/src/tests/checks/utils/modules.py 2>&1)
    [ $? -ne 0 ] && echo "$modules" && return 1
    local ret; ret=0
    for module in $modules
    do
        check_module "$module"
        [ $? -ne 0 ] && ret=1
    done
    return $ret
}

main() {
    mkdir /drone/src/conf &&
        init_bin &&
        init_conf &&
        link_modules &&
        check_modules
}

main
